export type PlanId = 'community' | 'starter' | 'business' | 'enterprise';

interface PlanDef {
  features: Record<string, boolean>;
  limits: Record<string, number>; // -1 = unlimited
}

export const PLANS: Record<PlanId, PlanDef> = {
  community: {
    features: {
      ticketing:       true,   // always available
      // TicketPilot add-ons
      ai_rag:          false,
      kb:              false,
      know_base:       false,
      sla_config:      false,
      analytics:       false,
      monthly_reports: false,
      audit_log:       false,
      // Strata modules
      assets:          false,
      contracts:       false,
      procurement:     false,
      service_hub:     false,
      patches:         false,
      cost_lens:       false,
      change_board:    false,
      incidents:       false,
      flowbot:         false,
      status_cast:     false,
      people_sync:     false,
      billing:         false,
    },
    // agents=10 for community (was 5 — phase-H team seat cap fix on main)
    limits: { agents: 10, ai_queries: 0 },
  },
  starter: {
    features: {
      ticketing:       true,
      ai_rag:          true,
      kb:              true,
      know_base:       true,
      sla_config:      true,
      analytics:       false,
      monthly_reports: false,
      audit_log:       false,
      assets:          true,
      contracts:       true,
      procurement:     true,
      service_hub:     true,
      patches:         false,
      cost_lens:       false,
      change_board:    false,
      incidents:       false,
      flowbot:         false,
      status_cast:     false,
      people_sync:     false,
      billing:         true,
    },
    limits: { agents: -1, ai_queries: 5_000 },
  },
  business: {
    features: {
      ticketing:       true,
      ai_rag:          true,
      kb:              true,
      know_base:       true,
      sla_config:      true,
      analytics:       true,
      monthly_reports: true,
      audit_log:       true,
      assets:          true,
      contracts:       true,
      procurement:     true,
      service_hub:     true,
      patches:         true,
      cost_lens:       true,
      change_board:    true,
      incidents:       true,
      flowbot:         true,
      status_cast:     true,
      people_sync:     false,
      billing:         true,
    },
    limits: { agents: -1, ai_queries: 25_000 },
  },
  enterprise: {
    features: {
      ticketing:       true,
      ai_rag:          true,
      kb:              true,
      know_base:       true,
      sla_config:      true,
      analytics:       true,
      monthly_reports: true,
      audit_log:       true,
      assets:          true,
      contracts:       true,
      procurement:     true,
      service_hub:     true,
      patches:         true,
      cost_lens:       true,
      change_board:    true,
      incidents:       true,
      flowbot:         true,
      status_cast:     true,
      people_sync:     true,
      billing:         true,
    },
    limits: { agents: -1, ai_queries: -1 },
  },
};

// Minimum plan required to unlock each feature (for upgrade messaging)
export const FEATURE_MIN_PLAN: Record<string, PlanId> = {
  ticketing:       'community',
  ai_rag:          'starter',
  kb:              'starter',
  know_base:       'starter',
  sla_config:      'starter',
  analytics:       'business',
  monthly_reports: 'business',
  audit_log:       'business',
  assets:          'starter',
  contracts:       'starter',
  procurement:     'starter',
  service_hub:     'starter',
  patches:         'business',
  cost_lens:       'business',
  change_board:    'business',
  incidents:       'business',
  flowbot:         'business',
  status_cast:     'business',
  people_sync:     'enterprise',
  billing:         'starter',
};
